title: "Being Vardaan"
description: "Digital Lead | Architect | Payments | Fintech | Product | Engineering"
author: "Vardaan Gupta"
lang: en
theme: jekyll-professional-resume
favicon: "/favicon.ico"
url: "https://vardaan-gupta.github.io"
# Social links (uncomment or add as needed)
linkedin: "https://linkedin.com/in/vardaanconnected"
github: "https://github.com/vardaan-gupta"
# twitter: "https://twitter.com/your-twitter"
