name: Deploy Site

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  set-deploy-type:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.set-output.outputs.target }}
    steps:
      - uses: actions/checkout@v4

      - name: get deployment target
        run: |
          TARGET=$(cat DEPLOY_STRATEGY)
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: check if target is valid
        if: success() && !contains(fromJSON('["gh-pages", "firebase", "none"]'), env.TARGET)
        run: echo 'Invalid Deployment Target' && exit 1

      # gh actions doesn't support using the 'env' context on job level ifs for
      # some reason smh. here we use outputs instead
      - name: set output to deploy target
        id: set-output
        run: echo "::set-output name=target::${{ env.TARGET }}"

  # not sure if anyone wants this but I'm putting this here for those that don't
  # want to host their site. else the actions will show an annoying x whenever
  # you push to master
  deploy-none:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: needs.set-deploy-type.outputs.target == 'none'
    steps:
      - run: echo 'No Deployment Specified' && exit 0

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: needs.set-deploy-type.outputs.target == 'gh-pages'
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-firebase:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: needs.set-deploy-type.outputs.target == 'firebase'

    steps:
      - uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: build jekyll
        run: |
          bundle install
          bundle exec jekyll build

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
